# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JamieBoyd.net
email: enkizero@gmail.com
description: Jamie Boyd is a web developer and designer living and working in Glasgow, Scotland. This is his own little bit of the internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamieboyd.net" # the base hostname & protocol for your site
twitter_username: jamboid
github_username:  jamboid

# Build settings
markdown: kramdown

# Sass
# sass:
#     style: compressed

# Excludes
exclude: [config.codekit3, config.codekit, Gemfile, Gemfile.lock]
